### ISSUE TITLE
校验失败Cross-Origin Read Blocking (CORB) blocked cross-origin

### ISSUE THREAD

**Issue by Aniderr** [llblh/vue-tencent-captcha#2]
请问报一下问题 用你的这套的话 应该如何处理呢？
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://dj.captcha.qq.com/caplog?appid=20128&1=0&2=0&3=0&4=0&5=1554282763648&6=1554282763648&7=1554282763648&8=1554282763648&9=1554282763648&10=1554282763654&11=1554282763703&12=1554282763740&13=1554282763717&14=1554282764114&15=1554282764616&16=1554282764625&17=0&18=0&19=0&20=1011&21=919&22=0&23=55&24=0&29=2012059542&31=3641862071&32=0&33=&34=6675593633314910471&35=549&36=549&37=0&42=0&43=59&44=412&45=249&46=1011&47=235&49=31&platform=ios&flag1=21408&flag2=3&flag3=14&subsid=5 with MIME type text/json

**Comment by llblh** [comment]
是不是你的配置域名不对？

组件只是做了一下封装，不会涉及数据请求
