### ISSUE TITLE
麻烦有空更新一下 npm package 版本

### ISSUE THREAD

**Issue by Ncaffeine** [llblh/vue-tencent-captcha#8]
``
麻烦有空更新一下 npm package 版本, 我们会立即更新您的库，感谢您提供的lib
``

**Comment by llblh** [comment]
> `麻烦有空更新一下 npm package 版本, 我们会立即更新您的库，感谢您提供的lib`

版本已经更新了。

不好意思，最近在忙其它的事情，抱歉了
